import { useEffect } from 'react'
import { Link } from 'react-router-dom'

export default function Terms() {
  useEffect(() => {
    document.title = 'Terms of Service — Success & Sobriety'
    window.scrollTo(0, 0)
  }, [])

  return (
    <>
    <main className="legal-page">
      <div className="legal-inner">
        <Link to="/" className="legal-back">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M19 12H5M12 19l-7-7 7-7"/></svg>
          Back to Home
        </Link>
        <h1 className="legal-title">Terms of Service</h1>
        <p className="legal-updated">Last updated: 19 March 2026</p>

        <section className="legal-section">
          <h2>1. About These Terms</h2>
          <p>
            These terms govern your use of the Success & Sobriety mobile application and website
            (collectively, the "Service") operated by S&S Ltd ("we", "us", "our").
            By using the Service, you agree to these terms.
          </p>
        </section>

        <section className="legal-section">
          <h2>2. The Service</h2>
          <p>
            Success & Sobriety is a personal wellness and sobriety tracking application. It provides:
          </p>
          <ul>
            <li>Sobriety day counting and milestone tracking</li>
            <li>Daily mood, energy, and productivity logging</li>
            <li>AI-powered coaching conversations</li>
            <li>Wellness exercises (breathing, grounding, body scan)</li>
            <li>Situational strategy guides (the Playbook)</li>
            <li>Educational content about sobriety and health</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>3. Important Disclaimer</h2>
          <p>
            <strong>Success & Sobriety is not a medical service.</strong> The app is a personal wellness tool
            and does not provide medical advice, diagnosis, or treatment. The AI coach is not a licensed therapist,
            counsellor, or medical professional.
          </p>
          <p>
            If you are experiencing a medical emergency, alcohol withdrawal symptoms, or suicidal thoughts,
            please contact emergency services (999), the Samaritans (116 123), or your GP immediately.
          </p>
          <p>
            The app should complement, not replace, professional medical care. Always consult healthcare
            professionals for medical decisions related to alcohol dependency or withdrawal.
          </p>
        </section>

        <section className="legal-section">
          <h2>4. Account & Eligibility</h2>
          <ul>
            <li>You must be 18 years or older to use the Service</li>
            <li>You must provide a valid email address to create an account</li>
            <li>You are responsible for maintaining the security of your account</li>
            <li>You agree to provide accurate information</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>5. Subscriptions & Payments</h2>
          <p>
            The Service offers a free trial period and paid subscription tiers:
          </p>
          <ul>
            <li><strong>Free Trial:</strong> 30 days of full access to all features</li>
            <li><strong>Premium:</strong> £9.99/month — unlimited AI coaching, all features</li>
            <li><strong>Sober Support:</strong> £150/month — Premium features plus professional coaching sessions</li>
          </ul>
          <p>
            Subscriptions are managed through the Apple App Store or Google Play Store.
            Renewal and cancellation terms are governed by the respective store's policies.
          </p>
        </section>

        <section className="legal-section">
          <h2>6. AI Coach</h2>
          <ul>
            <li>The AI coach provides general wellness guidance, not medical advice</li>
            <li>AI responses are generated by third-party language models and may not always be accurate</li>
            <li>The coach is hardcoded to support abstinence and will never suggest moderation</li>
            <li>If crisis language is detected, the app will surface professional helpline information</li>
            <li>Conversations are not stored on our servers beyond the active session</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>7. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to gain unauthorised access to other users' data</li>
            <li>Reverse-engineer, decompile, or disassemble the app</li>
            <li>Use the Service to harm, harass, or threaten others</li>
            <li>Share your account credentials with others</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>8. Intellectual Property</h2>
          <p>
            All content, design, code, and trademarks within the Service are owned by S&S Ltd.
            Your personal data (journal entries, debrief logs) remains your property.
            You grant us a limited licence to store and process your data solely to provide the Service.
          </p>
        </section>

        <section className="legal-section">
          <h2>9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, S&S Ltd is not liable for any indirect, incidental,
            or consequential damages arising from your use of the Service. Our total liability is limited
            to the amount you paid for the Service in the 12 months preceding the claim.
          </p>
          <p>
            We do not guarantee that the Service will be uninterrupted, error-free, or secure at all times.
          </p>
        </section>

        <section className="legal-section">
          <h2>10. Termination</h2>
          <p>
            You may delete your account at any time through the app or by contacting support@successandsobriety.com.
            We may suspend or terminate your account if you violate these terms.
          </p>
        </section>

        <section className="legal-section">
          <h2>11. Changes to Terms</h2>
          <p>
            We may update these terms from time to time. Continued use of the Service after changes
            constitutes acceptance of the updated terms. We will notify you of significant changes.
          </p>
        </section>

        <section className="legal-section">
          <h2>12. Governing Law</h2>
          <p>
            These terms are governed by the laws of England and Wales. Any disputes will be subject
            to the exclusive jurisdiction of the courts of England and Wales.
          </p>
        </section>

        <section className="legal-section">
          <h2>13. Contact</h2>
          <p>
            For questions about these terms:<br />
            <strong>Email:</strong> support@successandsobriety.com<br />
            <strong>Address:</strong> S&S Ltd, United Kingdom
          </p>
        </section>
      </div>
    </main>
    </>
  )
}
